In [3]:
#1.Write  a  NumPy  program  to  create  an  element-wise  comparison  (greater,  greater_equal,  less 
#and less_equal) of two given arrays.

import numpy as np
l1 = np.array([3,2])
l2 = np.array([3,4])
print("greatest: ")
print(np.greater(l1,l2))
print("greatest equal: ")
print(np.greater_equal(l1,l2))
print("less : ")
print(np.less(l1,l2))
print("less equal : ")
print(np.less_equal(l1,l2))

greatest: 
[False False]
greatest equal: 
[ True False]
less : 
[False  True]
less equal : 
[ True  True]


In [42]:
#2.Write a NumPyprogram to create an array of all the even integers from 30 to 70.
import numpy as np
list= np.arange(30,71)
print("array of all even integers from 30 to 70 is : ")
print(list)

array of all even integers from 30 to 70 is : 
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [43]:
#3.Write a NumPy program to create a 3x3 identity matrix.
import numpy as np
list= np.identity(3)
print("the 3x3 identity matrix is :")
print(list)

the 3x3 identity matrix is :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
#4.Write  a  NumPy  program  to  create  a  vector  with  values from  0  to  20 
#and  change  the  sign  of the numbers in the range from 9 to 15.
import numpy as np
l = np.arange(21)
l[(l>=9)&(l<=15)]*=-1
print("the resultant array is :")
print(l)

the resultant array is :
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [45]:
#5.Write  a  NumPy  program  to  create  a  5x5  zero  matrix  with  elements  
#on  the  main  diagonal equal to 1, 2, 3, 4, 5.
import numpy as np
l=np.diag([1,2,3,4,5])
print("the array is")
print(l)

the array is
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [46]:
#6.Write  a  NumPy  program  to  compute  sum  of  all  elements,  
#sum  of  each  column  and  sum  of each row of a given array
import numpy as np
l=np.array([[1,2],[3,4]])
print("the sum of all elements is")
print(np.sum(l))
print("row sum is")
print(np.sum(l,axis=1))
print("coloumn sum is: ")
print(np.sum(l,axis=0))

the sum of all elements is
10
row sum is
[3 7]
coloumn sum is: 
[4 6]


In [52]:
#7.Write a NumPy program to save a given array to a text file and load it.
import numpy
List = [5,4,3,2,1]
Array = numpy.array(List)
file = open("file1.txt", "w+")
content = str(Array)
file.write(content)
file.close()
file = open("file1.txt", "r")
content = file.read()
print("new contents of the file are", content)
file.close()

new contents of the file are [5 4 3 2 1]


In [47]:
#8.Write a NumPy program to check whether two arrays are equal (element wise) or not.
import numpy as np
l1=np.array([3,2,1])
l2=np.array([3,2,1])
print(np.equal(l1,l2))

[ True  True  True]


In [49]:
#9.Write  a  NumPy  program  to  create  a  4x4  array  with  random  values,  now  create  a  new  array from the said 
#array swapping first and last rows
import numpy as np
l=np.random.rand(4,4)
print("the original array is:")
print(l)
l[[0,3]]=l[[3,0]]
print("the resultant array is :")
print(l)

the original array is:
[[0.82290605 0.60811672 0.43088652 0.4219363 ]
 [0.45292878 0.67497055 0.63345777 0.45708509]
 [0.65579845 0.86874114 0.13752558 0.03053112]
 [0.55628046 0.45290676 0.58798234 0.07967176]]
the resultant array is :
[[0.55628046 0.45290676 0.58798234 0.07967176]
 [0.45292878 0.67497055 0.63345777 0.45708509]
 [0.65579845 0.86874114 0.13752558 0.03053112]
 [0.82290605 0.60811672 0.43088652 0.4219363 ]]


import numpy as np
l1=np.array([1,2,3])
l2=np.array([1,2,3])
if(l1==l2):
    print(np.multiply(l1,l2))

In [50]:
#10.Write a NumPy program to multiply two given arrays of same size element-by-element.
import numpy as np 
l1=np.array([1,2,3]) 
l2=np.array([1,4,3]) 
print("array after multiplication")
print(np.multiply(l1,l2))

array after multiplication
[1 8 9]
